"Steven Liss
"18 June 09
"_vimrc
"
set nocompatible     "use vim extras not available in vi
source $VIMRUNTIME/vimrc_example.vim
behave mswin

colorscheme evening  "pretty colors
set cursorline       "set the cursor to be a line

set nowrap           "no word wrap
set number           "show line numbers

"make tabs into four spaces
set expandtab
set tabstop=4


"highlight EmptyLines ctermbg=yellow guibg=yellow
"match EmptyLines /^\s*$/


"set diffexpr=MyDiff()
"function MyDiff()
"    let opt = ''
"    if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
"    if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
"    silent execute '\"!C:\Program Files\vim\diff\" -a ' . opt . v:fname_in . ' ' . v:fname_new . ' > ' . v:fname_out
"endfunction


if has("gui_running")
    set guifont=Intel\ One\ Mono:h8
    set guioptions-=T
    if has("directx")
        set renderoptions=type:directx
    endif
    let s:geom = has("win32") ? expand("~/vimfiles/geometry.vim") : expand("~/.vim/geometry.vim")
    if filereadable(s:geom)
        execute "source" fnameescape(s:geom)
    endif
endif

"keep the caret in the middle half, both axes
set sidescroll=1
augroup ScrollMargins
    autocmd!
    autocmd VimEnter,VimResized * let &scrolloff = &lines / 4 | let &sidescrolloff = &columns / 4
augroup END

function! s:GlucDir() abort
    return has('win32') ? $LOCALAPPDATA . '/gluc' : expand('~/.local/share/gluc')
endfunction

function! s:GlucSend(verb, payload) abort
    let l:file = s:GlucDir() . '/endpoint'
    if !filereadable(l:file) | return | endif
    let l:endpoint = readfile(l:file, '', 2)
    if len(l:endpoint) < 2 | return | endif
    try
        let l:channel = ch_open('127.0.0.1:' . l:endpoint[0],
            \ { 'mode': 'raw', 'waittime': 200 })
    catch
        return
    endtry
    if ch_status(l:channel) !=# 'open' | return | endif
    let l:body = json_encode(a:payload)
    call ch_sendraw(l:channel, join([
        \ 'POST /' . a:verb . ' HTTP/1.1',
        \ 'Host: 127.0.0.1',
        \ 'Authorization: Bearer ' . l:endpoint[1],
        \ 'Content-Type: application/json',
        \ 'Content-Length: ' . strlen(l:body),
        \ 'Connection: close',
        \ '', l:body], "\r\n"))
endfunction

function! s:GlucEvent(kind) abort
    if &buftype !=# '' | return | endif
    let l:file = expand('%:p')
    if empty(l:file) || !filereadable(l:file) | return | endif
    call s:GlucSend('event', {
        \ 'kind': a:kind,
        \ 'source': 'vim',
        \ 'osObject': { 'pid': getpid() },
        \ 'path': l:file,
        \ 'bag': { 'line': line('.') } })
endfunction

augroup GlucRecent
    autocmd!
    autocmd BufEnter * silent! call s:GlucEvent('select')
    autocmd BufLeave,VimLeavePre * silent! call s:GlucEvent('close')
    autocmd BufWritePost * silent! call s:GlucEvent('write')
augroup END
