"Steven Liss
"18 June 09
"_vimrc
"
set nocompatible     "use vim extras not available in vi
source $VIMRUNTIME/vimrc_example.vim
behave mswin

"swap, backup and undo out of the working tree - // keeps the full path in the
"name, so same-named files in different projects do not collide
let s:vimtmp = has("win32") ? expand("~/vimfiles/tmp") : expand("~/.vim/tmp")
for s:sub in ["swap", "backup", "undo"]
    if !isdirectory(s:vimtmp . "/" . s:sub)
        call mkdir(s:vimtmp . "/" . s:sub, "p")
    endif
endfor
let &directory = s:vimtmp . "/swap//"
let &backupdir = s:vimtmp . "/backup//"
let &undodir   = s:vimtmp . "/undo//"

colorscheme evening  "pretty colors
set cursorline       "set the cursor to be a line

set nowrap           "no word wrap
set number           "show line numbers

"make tabs into four spaces
set expandtab
set tabstop=4


"highlight EmptyLines ctermbg=yellow guibg=yellow
"match EmptyLines /^\s*$/


"set diffexpr=MyDiff()
"function MyDiff()
"    let opt = ''
"    if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
"    if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
"    silent execute '\"!C:\Program Files\vim\diff\" -a ' . opt . v:fname_in . ' ' . v:fname_new . ' > ' . v:fname_out
"endfunction


if has("gui_running")
    set guifont=Intel\ One\ Mono:h8
    set guioptions-=T
    if has("directx")
        set renderoptions=type:directx
    endif
    let s:geom = has("win32") ? expand("~/vimfiles/geometry.vim") : expand("~/.vim/geometry.vim")
    if filereadable(s:geom)
        execute "source" fnameescape(s:geom)
    endif
endif

"a diff gets two cells - one cannot hold two panes of real code
augroup GlucDiff
    autocmd!
    autocmd VimEnter * if &diff && exists("*GlucBand") | call GlucBand("2x1") | endif
augroup END

set diffopt=internal,filler,closeoff
"added one at a time: an old vim rejects the whole string over one value it
"does not know, and linematch needs 9.0.1000
silent! set diffopt+=algorithm:histogram
silent! set diffopt+=indent-heuristic
silent! set diffopt+=linematch:60
set fillchars+=diff:/

"changed span is loud on purpose: brightness and weight, not another pastel
highlight DiffAdd    guibg=#14361a guifg=NONE    gui=NONE
highlight DiffDelete guibg=#3a1618 guifg=#7a5254 gui=NONE
highlight DiffChange guibg=#16283c guifg=NONE    gui=NONE
highlight DiffText   guibg=#ffd75f guifg=#101010 gui=bold,underline

"keep the caret in the middle half, both axes
set sidescroll=1
augroup ScrollMargins
    autocmd!
    autocmd VimEnter,VimResized * let &scrolloff = &lines / 4 | let &sidescrolloff = &columns / 4
augroup END
